age = int(input("Enter your age: "))
name = input("Enter your name: ")
#weight = float(input("Enter your weight: "))
weight = input("Enter your weight: ")
print(f"{name} you are {age} years old and you have {weight}.")
